// <auto-generated />
namespace warehouse_manager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class provider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(provider));
        
        string IMigrationMetadata.Id
        {
            get { return "202102282349291_provider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
